global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: qbittorrent
    static_configs:
      - targets: ["qbittorrent-exporter:8000"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: linker
    static_configs:
      - targets: ["linker:8000"]
